site_name: pulsefig
site_url: https://kyrylo-gr.github.io/pulsefig/
repo_url: https://github.com/kyrylo-gr/pulsefig/
theme:
  name: material
  logo: images/pulsefig-logo-small.png
  favicon: images/favicon.ico
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight
copyright: Library published by <a href="//kyrylo.gr/" target="_blank">kyrylo.gr</a> © 2024
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              returns_type_in_property_summary: false
            inherited_members: true
            filters:
              - '!^_' # exclude all members starting with _
              # - '^__init__$' # but always include __init__ modules and methods
              - '^__new__$' # but always include __new__ methods
              - '^__getitem__$'
              - '^__setitem__$'
            show_source: true
            show_submodules: true
            show_bases: true
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: true
            show_object_full_path: false
            show_symbol_type_heading: false
            show_symbol_type_toc: true
            docstring_style: google
            docstring_section_style: table
            members_order: source
            show_signature: true
            show_signature_annotations: false
            separate_signature: true
            unwrap_annotated: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: starting_guide/install
      - First steps: starting_guide/first_steps
      - Examples: examples

  - Releases: releases/
  - About: about/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
